baseURL: http://marcbuch.github.io/
languageCode: en-us
title: Marc Buchardt
theme: PaperMod

params:
  homeInfoParams:
    Title: Hello there
    Content: Welcome

  socialIcons:
    - name: github
      url: https://github.com/MarcBuch
